app = "goldeye-bot"
primary_region = "sin"

[build]

[[mounts]]
  source = "goldeye_data"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
